// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEIVHhO6oIYv2CtXpQ6hcIzIJjXHZcfLQ',
    appId: '1:187704860363:web:8ec34c71db66876a21454e',
    messagingSenderId: '187704860363',
    projectId: 'jafisdemodb',
    authDomain: 'jafisdemodb.firebaseapp.com',
    storageBucket: 'jafisdemodb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8nGpgEkHr2ZUqAM3ZMB-sgb9Y49ABi-g',
    appId: '1:187704860363:android:a98ecdec76d8a41921454e',
    messagingSenderId: '187704860363',
    projectId: 'jafisdemodb',
    storageBucket: 'jafisdemodb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXDRnLUiasx3LObJ0yyQZaWnwbiP-Fa9U',
    appId: '1:187704860363:ios:c14df987aa1b689721454e',
    messagingSenderId: '187704860363',
    projectId: 'jafisdemodb',
    storageBucket: 'jafisdemodb.appspot.com',
    iosClientId: '187704860363-abf8f332rglujeg4u3na44gac7nt8s8f.apps.googleusercontent.com',
    iosBundleId: 'com.example.firStorage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXDRnLUiasx3LObJ0yyQZaWnwbiP-Fa9U',
    appId: '1:187704860363:ios:c14df987aa1b689721454e',
    messagingSenderId: '187704860363',
    projectId: 'jafisdemodb',
    storageBucket: 'jafisdemodb.appspot.com',
    iosClientId: '187704860363-abf8f332rglujeg4u3na44gac7nt8s8f.apps.googleusercontent.com',
    iosBundleId: 'com.example.firStorage',
  );
}
